### ISSUE TITLE
Why your Heroku demo app has server side rendering?

### ISSUE THREAD

**Issue by vlafiser** [robgraeber/react-client-side#1]
Can you help me, how I can add server side rendering to this template?
I saw, your demo project it has, because I can see the HTML from browser.

Thank you so much!

**Comment by robgraeber** [comment]
Hey you have to run the server w/ NODE_ENV=production, you can see how it works in render.js. It only renders the static portions of the app. I have a react-ssr project on github w/ full server-side rendering using yahoo's dispatchr but it's a lot more complicated
